
import React from 'react';
import ReactMarkdown from 'react-markdown';
import { X, Sparkles, TrendingUp, BrainCircuit } from 'lucide-react';

interface LifeAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  content: string;
}

export const LifeAnalysisModal: React.FC<LifeAnalysisModalProps> = ({ isOpen, onClose, content }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-indigo-950/80 backdrop-blur-md transition-opacity"
        onClick={onClose}
      ></div>

      {/* Content Container */}
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[85vh] flex flex-col relative z-10 animate-in zoom-in-95 duration-300 border border-indigo-100 overflow-hidden">
        
        {/* Header */}
        <div className="px-8 py-6 border-b border-indigo-50 bg-gradient-to-r from-indigo-50 to-white flex justify-between items-center shrink-0">
          <div className="flex items-center gap-4">
             <div className="p-3 bg-indigo-600 rounded-xl shadow-lg shadow-indigo-200">
                <Sparkles className="w-6 h-6 text-white" />
             </div>
             <div>
                <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                    Life OS Analysis
                    <span className="px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 text-[10px] font-bold uppercase tracking-wider">30 Days</span>
                </h2>
                <p className="text-sm text-slate-500">AI-Powered Insights based on your tasks, finance, and logs.</p>
             </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-full text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-8 bg-white">
            {content ? (
                <article className="prose prose-slate prose-headings:font-bold prose-h1:text-indigo-900 prose-h2:text-slate-800 prose-a:text-indigo-600 max-w-none">
                    <ReactMarkdown>{content}</ReactMarkdown>
                </article>
            ) : (
                <div className="h-64 flex flex-col items-center justify-center text-slate-400 gap-4">
                    <BrainCircuit className="w-12 h-12 animate-pulse text-indigo-300" />
                    <div className="text-center">
                        <p className="text-lg font-semibold text-slate-600">Generating Intelligence...</p>
                        <p className="text-sm">Analyzing your last 30 days of data.</p>
                    </div>
                </div>
            )}
        </div>
        
        {/* Footer */}
        <div className="px-8 py-4 bg-slate-50 border-t border-slate-100 text-center text-xs text-slate-400">
            Analysis generated by Gemini 3 Flash • Private & Secure
        </div>

      </div>
    </div>
  );
};
